spring:
  application:
    name: consumer

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: suriya-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.consumer.entity
        spring.json.value.default.type: com.example.consumer.entity.Employee

server:
  port: 8082
